### ISSUE TITLE
unicode error during adding issiue

### ISSUE THREAD

**Issue by spinus** [glogiotatidis/gitissius#6]
``` bash
$ git issius new
```

``` bash
Title (None): 
 > Title cannot be empty.
Title (None): Error
Type (bug) [b/f/h]: b
Severity (low) [h/m/l/h]: m
Reported From (SOME UNICODE IN NAME!!!): 
Assigned To (None): myname
Status (new) [a/n/c/i/h]: 
Description (End with a line containing only '.'): 
 .
Create issue (y)? y
```

``` python
Traceback (most recent call last):
  File "/home/spinus/usr/opt/lpython/bin/git-issius", line 9, in <module>
    load_entry_point('Gitissius==0.1.6', 'console_scripts', 'git-issius')()
  File "/home/spinus/usr/opt/lpython/lib/python2.7/site-packages/Gitissius-0.1.6-py2.7.egg/gitissius/gitissius.py", line 104, in main
    commands.command[command](sys.argv[2:])
  File "/home/spinus/usr/opt/lpython/lib/python2.7/site-packages/Gitissius-0.1.6-py2.7.egg/gitissius/commands/__init__.py", line 17, in __call__
    return self._execute(options, args)
  File "/home/spinus/usr/opt/lpython/lib/python2.7/site-packages/Gitissius-0.1.6-py2.7.egg/gitissius/commands/new_issue.py", line 28, in _execute
    common.git_repo[issue.path] = issue.serialize(indent=4)
  File "/home/spinus/usr/opt/lpython/lib/python2.7/site-packages/Gitissius-0.1.6-py2.7.egg/gitissius/database.py", line 70, in serialize
    item_data = item.serialize()
  File "/home/spinus/usr/opt/lpython/lib/python2.7/site-packages/Gitissius-0.1.6-py2.7.egg/gitissius/properties.py", line 113, in serialize
    'value': unicode(self.value)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 9: ordinal not in range(128)
```

**Comment by glogiotatidis** [comment]
Thxn for your bug report. I'm looking into this

**Comment by mcepl** [comment]
```
The following changes since commit 748ad1f2ed16fe1e5807097c4c2ab72b91937c72:

  Changed bash completion to suggest all issius. (2013-02-15 23:32:36 +0100)

are available in the git repository at:

  git@gitorious.org:gitissius/gitissius.git unicode_fix

for you to fetch changes up to 287a1ce9e5e8218b337bac93738351c8e04c38d9:

  Fix Unicode and datetime.datetime serialization issues. (2013-09-02 17:06:26 +0200)

----------------------------------------------------------------
Matěj Cepl (1):
      Fix Unicode and datetime.datetime serialization issues.

 gitissius/database.py   | 18 +++++++++++++++++-
 gitissius/gitissius     |  1 +
 gitissius/gitissius.py  |  3 +++
 gitissius/properties.py |  2 +-
 4 files changed, 22 insertions(+), 2 deletions(-)
 create mode 120000 gitissius/gitissius
```
